version: "3.8"
services:

  
  #===================== https://portainer.docker.localhost/#!/1/docker/containers
  portainer:
    image: portainer/portainer-ce
    container_name: portainer_partner
    command: -H unix:///var/run/docker.sock
    depends_on: 
      - openssl
    ports:
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./docker/data/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http,https"
      - "traefik.http.routers.portainer.rule=Host(`portainer.docker.localhost`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls=true"
  #===================== https://traefik.docker.localhost
  traefik:
    image: traefik:2.5
    container_name: traefik_partner
    depends_on: 
      - openssl
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./docker/traefik/config.yml:/etc/traefik/config.yml:ro
      - ./docker/certs:/etc/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"

  #=====================
  openssl:
    build: ./docker/openssl
    image: openssl:1.0
    container_name: openssl_partner
    volumes:
      - ./docker/openssl:/openssl
      - ./docker/openssl/domains.ext:/domains.ext
      - ./docker/certs:/certs
  