http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      # middlewares:
      #   - cors
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
  # middlewares:
  #   cors:
  #     headers:
  #       accessControlAllowMethods:
  #         - OPTIONS
  #         - POST
  #         - HEAD
  #         - GET
  #       accessControlAllowOriginList:
  #         - http://portail-partner.docker.localhost
  #         - https://portail-partner.docker.localhost
  #         - http://api-partner.docker.localhost
  #         - https://api-partner.docker.localhost
  #         - http://traefik.docker.localhost
  #         - https://traefik.docker.localhost
  #         - http://localhost:8082
  #         - http://localhost:8083

  #       accessControlAllowCredentials: "true"
  #       addVaryHeader: "true"
  #       sslRedirect: "true"
  #       accessControlAllowHeaders: "*"
tls:
  certificates:
    - certFile: /etc/certs/localhost.crt
      keyFile: /etc/certs/localhost.key